name: quickbite
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.5
  curved_navigation_bar: ^1.0.6
  random_string: ^2.3.1
  http: ^1.2.2
  flutter_stripe: ^11.2.0
  shared_preferences: ^2.0.15
  flutter_secure_storage: ^9.2.2
  firebase_core: ^3.8.0
  firebase_analytics: ^11.3.5
  image_picker: ^1.1.2
  firebase_storage: ^12.3.6
  path_provider: ^2.1.5
  permission_handler: ^10.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - images/

